main/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("register/", views.registerPage, name='register'),
    path("login/", views.loginPage, name='login'),
    path("logout/", views.logoutUser, name='logout'),
    path("", views.index, name='home'),
    path("add_review/<int:pk>", views.add_review, name='add_review'),
    path("about/", views.about, name='about'),
    path("contact/", views.contact, name='contact'),
    path("products/", views.products, name='products'),
    # path("category_products/<int:id>", views.category, name='category'),
    path("product_detail/<int:id>", views.product_detail, name='product_detail'),
    path("order/<int:pk>", views.order, name='order'),
    path("cart/", views.cart, name='cart'),
    path("delete/<int:id>", views.delete, name='delete'),
]

sixteen/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.contrib.auth import get_user_model
# from django.contrib.gis.db import models


User = get_user_model()


# class Category(models.Model):
#     title = models.CharField("Название", max_length=120, null=True)
#
#     def __str__(self):
#         return str(self.title)
#
#     class Meta:
#         verbose_name = "Категория"
#         verbose_name_plural = "Категории"


class Product(models.Model):
    OUTWEAR = 'outwear'
    PANTS = 'pants'
    SHOES = 'shoes'
    ACC = 'accessories'

    CHOICE_GROUP = {
        (OUTWEAR, 'outwear'),
        (PANTS, 'pants'),
        (SHOES, 'shoes'),
        (ACC, 'accessories'),
    }
    title = models.CharField("Название", max_length=100)
    sub_title = models.CharField("Краткое описание", max_length=100, null=True)
    description = models.TextField("Описание")
    composition = models.CharField("Состав", max_length=100, null= True)
    size = models.CharField("Размер", max_length=50, null=True)
    model = models.CharField("Модель и Образ", max_length=150, null=True)
    image = models.ImageField("Изображение",  upload_to="images/", null=True)
    price = models.DecimalField("Цена", default=0, max_digits=10, decimal_places=2)
    group = models.CharField(max_length=20, choices=CHOICE_GROUP, default=OUTWEAR)
    is_active = models.BooleanField("Активен", default=True)

    def __str__(self):
        return str(self.title)

    class Meta:
        verbose_name = "Товар"
        verbose_name_plural = "Товары"


class Comments(models.Model):
    user = models.ForeignKey(
        User,
        verbose_name="Пользователь",
        on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(
         Product,
         verbose_name="Новость",
         on_delete=models.CASCADE, null=True)
    text = models.TextField("Комментарий", null=True)
    created = models.DateTimeField("Дата добавления", auto_now_add=True, null=True)
    moderation = models.BooleanField("Модерация", default=False, null=True)

    class Meta:
        verbose_name = "Комментарий"
        verbose_name_plural = "Комментарии"

    def __str__(self):
        return "{}".format(self.user)


class Employee(models.Model):
    name = models.CharField("Фио сотрудника", max_length=100)
    position = models.CharField("Должность", max_length=100)
    image = models.ImageField("Изображение",  upload_to="images/", null=True)
    description = models.CharField("Описание", max_length=150)

    def __str__(self):
        return str(self.name)

    class Meta:
        verbose_name = "Сотрудник"
        verbose_name_plural = "Сотрудники"


class Message(models.Model):
    full_name = models.CharField("ФИО", max_length=150)
    email = models.EmailField("email", max_length=100)
    title = models.CharField("Заголовок", max_length=100)
    text = models.TextField("Текст", max_length=200)

    def __str__(self):
        return str(self.full_name)

    class Meta:
        verbose_name = "Сообщения"
        verbose_name_plural = "Сообщении"


class Order(models.Model):
    user = models.ForeignKey(
        User,
        verbose_name="Пользователь",
        on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    count = models.IntegerField("Количество")
    size = models.CharField("Размер", max_length=50)
    moderation = models.BooleanField("Модерация", default=False, null=True)

    def __str__(self):
        return "{}".format(self.user)

    class Meta:
        verbose_name = "Заказ"
        verbose_name_plural = "Заказы"


class Contact(models.Model):
    long_position = models.FloatField()
    lat_position = models.FloatField()
    country = models.CharField("Страна", max_length=30, null=True)
    city = models.CharField("Город", max_length=30, null=True)
    street = models.CharField("Улица", max_length=30, null=True)
    phone_number = models.CharField("Номер телефона", max_length=30, null=True)
    facebook = models.URLField("URl для facebook странице", null=True)
    twitter = models.URLField("URl для twitter странице", null=True)
    linkedin = models.URLField("URl для linkedin странице", null=True)
    behance = models.URLField("URl для behance странице", null=True)

    def __str__(self):
        return str(self.country)

    class Meta:
        verbose_name = "Адрес"
        verbose_name_plural = "Адреса"
# Create your models here.


# class Address(models.Model):
#     country = models.CharField("Страна", max_length=30)
#     city = models.CharField("Город", max_length=30)
#     street = models.CharField("Улица", max_length=30)
#     phone_number = models.CharField("Номер телефона", max_length=30)
#     facebook = models.URLField("URl для facebook странице")
#     twitter = models.URLField("URl для twitter странице")
#     linkedin = models.URLField("URl для linkedin странице")
#     behance = models.URLField("URl для behance странице")
#
#     def __str__(self):
#         return str(self.country)
#
#     class Meta:
#         verbose_name = "Адрес"

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms.widgets import EmailInput, TextInput, Textarea
from django.forms import ModelForm
from .models import Comments, Message, Order
from django.contrib.auth import authenticate, login


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ("text", )


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ("full_name", "email", "title", "text")

        widgets = {
            "full_name": TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'ФИО'
            }),
            "email": EmailInput(attrs={
                'class': 'form-control',
                'placeholder': "Email"
            }),
            "title": TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Заголовок'
            }),
            "text": Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Текст'
            })
        }


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ("count", "size")



class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Product, Comments, Employee, Order, Contact
from .form import ReviewForm, MessageForm, OrderForm,CreateUserForm
from django.core.paginator import Paginator
from django.http import HttpResponseNotFound

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_protect


def registerPage(request):
    form = CreateUserForm()
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('username')
            messages.success(request, 'Account was created for' + user)

            return redirect('login')

    context = {'form': form}

    return render(request, 'main/register.html', context)


def loginPage(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            messages.info(request, 'Username OR password is incorrect')

    context = {}
    return render(request, 'main/login.html', context)


def logoutUser(request):
    logout(request)
    return redirect('login')


def index(request):
    product = Product.objects.filter(is_active=False)
    return render(request, 'main/home.html', {
        'product_list': product
    })


def products(request):
    product_list = Product.objects.filter(is_active=True)
    # categories = Category.objects.all()
    paginator = Paginator(product_list, per_page=6)

    page_number = request.GET.get('page', 1)
    page_obj = paginator.get_page(page_number)

    return render(request, 'main/products.html', {
        'product_list': page_obj.object_list,
        # 'categories': categories,
        'paginator': paginator,
        'page_obj': page_obj,
        'page_number': int(page_number),
    })


def product_detail(request, id):
    product = Product.objects.get(id=id)
    form = ReviewForm()

    return render(request, 'main/product_detail.html', {
        'product': product,
        'form': form,


    })


# def product_review(request, pk):
#     form = ReviewForm(request.POST)
#     pro = Product.objects.get(id=pk)
#     if form.is_valid():
#         form = form.save(commit=False)
#         form.pro = pro
#         form.save()
#     return redirect(pro.get_absolute_url())


def add_review(request, pk):
    product = get_object_or_404(Product, id=pk)
    comment = Comments.objects.filter(product=product, moderation=True)
    if request.method == "POST":
        form = ReviewForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.user = request.user
            form.product = product
            form.save()
            return redirect(product_detail, pk)
    else:
        form = ReviewForm()
    return render(request, 'main/product_detail.html', {'product': product, 'form': form, 'comment': comment})


def about(request):
    employee = Employee.objects.all()
    return render(request, 'main/about.html', {
        'employee': employee
    })


def contact(request):
    addresses = Contact.objects.all()
    contact = Contact.objects.all().first()
    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('contact')
    else:
        form = MessageForm()
    return render(request, 'main/contact.html', {
        'form': form,
        'contact': contact,
        'addresses': addresses
    })


def order(request, pk):
    product = get_object_or_404(Product, id=pk)
    order = Order.objects.filter(product=product, moderation=True)
    if request.method == "POST":
        form = OrderForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.user = request.user
            form.product = product
            form.save()
            return redirect(product_detail, pk)
        else:
            form = OrderForm()
        return render(request, 'main/product_detail.html', {'product': product, 'form': form, 'order': order })


def cart(request):
    object = Order.objects.all()
    return render(request, 'main/cart.html', {
        'object': object
    })


def delete(request, id):
    try:
        item = Order.objects.get(id=id)
        item.delete()
        return redirect('cart')
    except Order.DoesNotExist:
        return HttpResponseNotFound("<h2>Товар не найден</h2>")


# def category(request, id):
#     categories = Category.objects.get(id=id)
#     queryset = Product.objects.filter(category=categories)
#
#     if queryset:
#         c = {'item': queryset,
#              }
#         return render(request, 'main/products.html', c)
#     else:
#         return render(request, 'main/products.html')

# Create your views here.

templates/main/cart.html
 {% extends 'base.html' %}
{% block content %}
{% load static %}

    <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="text-contents">
              <h4 class="text-center" style="font-size: 50px;font-weight: bold;margin-top: 150px;margin-bottom: 70px;font-family: system-ui;">Ваша корзина</h4>
            </div>
          </div>
        </div>
    </div>
    <div class="row row-cards" style="margin-left: 130px;">
      <div class="col-lg-10 col-md-10 col-sm-10 bootstrap snippets">
          <!-- Cart -->
          <div class="card">
              <div class="card-body hero-feature">
                  <div class="table-responsive push">
                      <table class="table table-bordered table-hover tbl-cart text-nowrap">
                          <thead>
                              <tr style="font-size: 18px;font-weight: bold;color: #3F3F3F">
                                  <td class="hidden-xs">Image</td>
                                  <td>Product Name</td>
                                  <td>Size</td>
                                  <td class="td-qty">Quantity</td>
                                  <td>Unit Price</td>
                                  <td>Sub Total</td>
                              </tr>
                          </thead>
                          <tbody>
                              {% for obj in object %}
                                  <tr>
                                      <td class="hidden-xs">
                                          <a href="#">
                                              <img src="{{ obj.product.image.url }}" alt=" " title="" width="100" height="120" style="position: center">
                                          </a>
                                      </td>
                                      <td><a style="font-size: 15px">{{ obj.product.title }} </a>
                                      </td>

                                      <td>
                                          <a>{{ obj.size }}</a>
                                      </td>
                                      <td>
                                          <a>{{ obj.count }}</a>
                                      </td>
                                      <td >$ {{ obj.product.price}}</td>
                                      <td>$ 122.21</td>
                                      <td class="text-center">
                                          <a href="{% url 'delete' obj.id %}" class="remove_cart" >
                                              <i class="fa fa-trash"></i>
                                          </a>
                                      </td>
                                  </tr>
                              {% endfor %}
                          </tbody>
                      </table>
                  </div>
                  <div class="float-left mt-2">
                      <div class="row">
                          <div class="col-8"><a href="{% url 'products' %}" class="btn btn-info mt-2"><i class="fa fa-arrow-circle-left"></i> Continue Shopping</a></div>
                      </div>
                  </div>
                  <div class=" float-right">
<!--                      <a href="cart.html" class="btn btn-warning mt-2">Update Cart</a>-->
                      <a href="#" class="btn btn-success mt-2">Checkout <i class="fa fa-arrow-circle-right"></i></a>
                  </div>

              </div>
          </div>
      </div>
    </div>
  </body>
{% endblock %}
								<!-- End Cart -->

templates/main/home.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
    <div class="wrapper">
        <div class="full-screen">
            <div class="full-screen__body">
                <div class="full-screen__title">SIXTEEN</div>
                <div class="full-screen__text">clothing</div>
            </div>
            <video autoplay muted loop preload="auto" class="full-screen__video">
                <source type="video/mp4" src="{% static 'love.mp4' %}">
            </video>
        </div>
        <div class="content">
            <div class="content__container">
                <div class="latest-products">
                  <div class="container">
                    <div class="row">
                      <div class="col-md-12">
                        <div class="section-heading">
                          <h2  style="font-size: 35px">Coming soon</h2>
                          <a href="{% url 'products' %}">view all products <i class="fa fa-angle-right"></i></a>
                        </div>
                      </div>
                      {% for product in product_list %}
                        <div class="col-md-4">
                          <div class="product-item " data-aos="fade-up" data-aos-duration="2000" style="width: 365px">
                            <img src="{{ product.image.url }}" alt="">
                            <a href="#" class="badge-corner" style="position: absolute;top: 0;right: 0;width: 0;height: 0;border-top: 66px solid #f33f3f;order-top-color: rgba(0, 0, 0, 0.3);border-left: 66px solid transparent;padding: 0;background-color: transparent;border-radius: 0;">
                              <span class="fa fa-star" style="position: absolute;top: -52px;left: -28px;font-size: 16px;color: #fff;"></span>
                            </a>
                            <div class="down-content">
                              <a><h4>{{ product.title }}</h4></a>
                              <h6>${{ product.price }}</h6>
                              <p>{{ product.sub_title }}</p>
                            </div>
                          </div>
                        </div>
                      {% endfor %}
                    </div>
                  </div>
                </div>

                <div class="best-features">
                  <div class="container">
                    <div class="row">
                      <div class="col-md-12">
                        <div class="section-heading">
                          <h2>О Sixteen Clothing</h2>
                        </div>
                      </div>
                      <div class="col-md-6">
                        <div class="left-content" data-aos="fade-right" data-aos-duration="2000">
                          <h4>Ищете лучшие продукты?</h4>
                          <p><a rel="nofollow" href="https://templatemo.com/tm-546-sixteen-clothing" target="_parent">This template</a> is free to use for your business websites. However, you have no permission to redistribute the downloadable ZIP file on any template collection website. <a rel="nofollow" href="https://templatemo.com/contact">Contact us</a> for more info.</p>
                          <ul class="featured-list">
                            <li><a href="#">Lorem ipsum dolor sit amet</a></li>
                            <li><a href="#">Consectetur an adipisicing elit</a></li>
                            <li><a href="#">It aquecorporis nulla aspernatur</a></li>
                            <li><a href="#">Corporis, omnis doloremque</a></li>
                            <li><a href="#">Non cum id reprehenderit</a></li>
                          </ul>
                          <a href="{% url 'about' %}" class="filled-button">Read More</a>
                        </div>
                      </div>
                      <div class="col-md-6">
                        <div class="right-image animate__animated animate__fadeInRight">
                          <img src="{% static 'assets/images/feature-image.jpg' %}" alt="">
                        </div>
                      </div>
                    </div>
                  </div>
                </div>


                <div class="call-to-action">
                  <div class="container">
                    <div class="row">
                      <div class="col-md-12">
                        <div class="inner-content" data-aos="zoom-in-up">
                          <div class="row">
                            <div class="col-md-8">
                              <h4>Creative &amp; Unique <em>Sixteen</em> Products</h4>
                              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque corporis amet elite author nulla.</p>
                            </div>
                            <div class="col-md-4">
                              <a href="#" class="filled-button">Purchase Now</a>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
            </div>
        </div>
      </div>
{% endblock %}

templates/main/product_detail.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
    <div class="row">
        <div class="col-md-12 wrapper wrapper-content animated fadeInRight">
            <div class="ibox card">
                 <div class="card-header">
                    <h3 class="card-title">Items in your cart</h3>
                    <div class="card-options ">
                        <a href="#" class="card-options-collapse" data-toggle="card-collapse"><i class="fe fe-chevron-up"></i></a>
                        <a href="#" class="card-options-remove" data-toggle="card-remove"><i class="fe fe-x"></i></a>
                    </div>
                </div>
                <div class="card-body">
                    <div class="ibox-content">
                        <div class="row">
                            <div class="col-md-12 col-lg-5">
                                <div class="cart-product-imitation">
                                    <img src="{{ product.image.url }}" width="500px" alt="">
                                </div>
                            </div>
                            <div class="col-md-12 col-lg-7">
                                <div class="card-body p-5">
                                    <h3 class="product_title"><a class="text-navy h2 font-weight-semibold mr-1">{{ product.title }}</a></h3>
                                    <p class="small_2">{{ product.sub_title }}</p>
                                    <h4 class="product_label">Состав:</h4>
                                    <p class="small">{{ product.composition }}</p>
                                    <h4 class="product_label">Модел и образ:</h4>
                                    <p class="small">{{ product.model }}</p>
                                    <dl class="small m-b-none">
                                        <dt>Описание:</dt>
                                        <dd>{{ product.description }}</dd>
                                    </dl>
                                    <h2 class="price" style="font-weight: bold">${{ product.price }}</h2>
                                    {% if user.is_active %}
                                        <button  type="button" class=" btn btn-pill btn-danger" data-toggle="modal" data-target="#myModal{{ product.id }}"><i class="fa fa-cart-plus"></i>Add to cart</button>
                                            <form action="{% url 'order' product.id %}" method="post">
                                            {% csrf_token %}
                                                <div class="modal fade" id="myModal{{ product.id }}" tabindex="-1" aria-labelledby="myModalLabel" aria-hidden="true">
                                                    <div class="modal-dialog" style="margin-top: 100px">
                                                        <div class="modal-content">
                                                            <div class="modal-header">
                                                                <h5 class="modal-title" id="myModalLabel" style="font-size: 20px; font-weight: bold; font-family: system-ui;">Продукт {{ product.id}}</h5>
                                                                <button class="close" data-bs-dismiss="modal">x</button>
                                                            </div>
                                                            <div class="modal-body">
        <!--                                                        <h6 class="text-center">ID Продукта {{ product.id }}</h6>-->
        <!--                                                        <label class="form-label_1", style="font-weight: bold">ID Продукта</label>-->
        <!--                                                         <input name="id" type="number" value="{{ product.id }}">-->
                                                                <label class="form-label_1", style="font-weight: bold">Количество</label>
                                                                <div class="number">
                                                                    <span class="minus">-</span>
                                                                    <input name="count" type="text" value="1"/>
                                                                    <span class="plus">+</span>
                                                                </div>
                                                                <label class="form-label_1", style="font-weight: bold">Размер</label>
                                                                <input name="size" type="text">
                                                            </div>
                                                            <div class ="modal-footer">
                                                                <button type="submit" class="btn btn-danger">Добавить</button>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </form>
                                            {% else %}
                                                <h4  style="margin-top: 25px;color: darkred;font-size: 15px">Авторизуйтесь для добавления в корзину</h4>
                                    {% endif %}
                                </div>
                                <div class="row">
                                    <div class="col-md-8 col-lg-5">
                                        <div class="card-body p-5">
                                            {% if user.is_active %}
                                                <form action="{% url 'add_review' product.id %}" method="post">
                                                    {% csrf_token %}
                                                    <div class="form-group">
                                                        <label class="form-label">Коментарии</label>
                                                        {{form.text}}
                                                    </div>
                                                    <button class="btn-outline-dark"><i class="fa fa-comments-o"></i>Отправить</button>
                                                </form>
                                                {% else %}
                                                    <div class="card_comment" style="width: 600px">
                                                        <div class="card-header">
                                                            <h3 class="card-title" style="font-weight: bold; font-size: 20px; font-family: cursive; align-items: center;">Коментарии</h3>
                                                            <div class="card-options">
                                                                <a href="#" class="card-options-collapse" data-toggle="card-collapse"><i class="fe fe-chevron-up"></i></a>
                                                                <a href="#" class="card-options-remove" data-toggle="card-remove"><i class="fe fe-x"></i></a>
                                                            </div>
                                                        </div>
                                                        <div class="card-alert alert alert-danger mb-0">
                                                            <h4 class="comment_else">Что бы оставить комментарий авторизуйтесь</h4>
                                                        </div>
                                                        <div class="card-body">
                                                            <a href="{% url 'login' %}" style="align-items: center">Авторизация</a>
                                                        </div>
                                                    </div>
    <!--                                                    <h4 class="comment_else">Что бы оставить комментарий авторизуйтесь</h4>-->
    <!--                                                    <button class="btn-outline-primary" type="submit">Авторизация</button>-->
                                            {% endif %}
                                            <div class="list">
                                                {% for comment in product.comments_set.all %}
                                                <h7 class="comment">{{ comment.user }}</h7>
                                                <p class="comment-text">{{ comment.text }}</p>
                                                {% endfor %}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Row -->
{% endblock %}